import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Providers from "./providers";
import { Roboto } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import NavLink from "./components/ui/NavLink";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
  display: "swap",
});
<NavLink href={"user/asdfhafh"}/>

const inter = Inter({ subsets: ["latin"] });

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {

  return (
    <html lang="en">
      <body className={`${roboto.className} ${playfairDisplay.variable}`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
